[package]
name = "bu"
version = "0.1.0"
authors = ["Lorenzo Affetti <lorenzo.affetti@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bo = {path = "../bo"}
